// EventMarker.swift
// GoviKey EventTap
//
// Marker value for self-generated synthetic events.
// Set on CGEvent.eventSourceUserData so the event tap can skip its own events.

import CoreGraphics

public enum EventMarker {
    /// Marker value set on all synthetic events generated by GoviKey.
    /// ASCII for "GOVI" = 0x474F5649
    static let goviKey: Int64 = 0x474F_5649

    /// Check if an event was generated by GoviKey.
    @inline(__always)
    static func isSelfGenerated(_ event: CGEvent) -> Bool {
        event.getIntegerValueField(.eventSourceUserData) == goviKey
    }

    /// Mark an event as generated by GoviKey.
    @inline(__always)
    static func markAsSelfGenerated(_ event: CGEvent) {
        event.setIntegerValueField(.eventSourceUserData, value: goviKey)
    }
}
