// EventMarker.swift
// VietKey EventTap
//
// Marker value for self-generated synthetic events.
// Set on CGEvent.eventSourceUserData so the event tap can skip its own events.

import CoreGraphics

public enum EventMarker {
    /// Marker value set on all synthetic events generated by VietKey.
    /// ASCII for "VKEY" = 0x564B4559
    static let vietKey: Int64 = 0x564B_4559

    /// Check if an event was generated by VietKey.
    @inline(__always)
    static func isSelfGenerated(_ event: CGEvent) -> Bool {
        event.getIntegerValueField(.eventSourceUserData) == vietKey
    }

    /// Mark an event as generated by VietKey.
    @inline(__always)
    static func markAsSelfGenerated(_ event: CGEvent) {
        event.setIntegerValueField(.eventSourceUserData, value: vietKey)
    }
}
